c_compiler:
- gcc
c_compiler_version:
- '12'
cdt_name:
- cos7
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
fontconfig:
- '2'
freetype:
- '2'
glib:
- '2'
icu:
- '73'
libpng:
- '1.6'
libxcb:
- '1.15'
pixman:
- '0'
target_platform:
- linux-armv7l
xz:
- '5'
zlib:
- '1.2'
cdt_arch:
- armv7l
